// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHVPeaytpMytOv0_Q8Oiz_M5oLgsRwPSA',
    appId: '1:423877510683:web:62c5ed156f93205cac1abe',
    messagingSenderId: '423877510683',
    projectId: 'flutter-firebase-codelab-c56a3',
    authDomain: 'flutter-firebase-codelab-c56a3.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-c56a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYGv3xLBgVWOpWcZx-3HnViN6L--nXUNQ',
    appId: '1:423877510683:android:69aa552b7f636018ac1abe',
    messagingSenderId: '423877510683',
    projectId: 'flutter-firebase-codelab-c56a3',
    storageBucket: 'flutter-firebase-codelab-c56a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0YO4YoN90p1EaqOpwsMvvJvcOm0WEKNI',
    appId: '1:423877510683:ios:ffdc0502c74df5f4ac1abe',
    messagingSenderId: '423877510683',
    projectId: 'flutter-firebase-codelab-c56a3',
    storageBucket: 'flutter-firebase-codelab-c56a3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0YO4YoN90p1EaqOpwsMvvJvcOm0WEKNI',
    appId: '1:423877510683:ios:ffdc0502c74df5f4ac1abe',
    messagingSenderId: '423877510683',
    projectId: 'flutter-firebase-codelab-c56a3',
    storageBucket: 'flutter-firebase-codelab-c56a3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHVPeaytpMytOv0_Q8Oiz_M5oLgsRwPSA',
    appId: '1:423877510683:web:5fe6773468ce05f9ac1abe',
    messagingSenderId: '423877510683',
    projectId: 'flutter-firebase-codelab-c56a3',
    authDomain: 'flutter-firebase-codelab-c56a3.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-c56a3.firebasestorage.app',
  );
}
