// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrUww1xSkkb_Bdar0rJ-iXUccxSxpT79E',
    appId: '1:926759717295:web:47743cce0048813cce875a',
    messagingSenderId: '926759717295',
    projectId: 'flutterauth-c90c6',
    authDomain: 'flutterauth-c90c6.firebaseapp.com',
    storageBucket: 'flutterauth-c90c6.firebasestorage.app',
    measurementId: 'G-JGPH8H2E22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoqYVdgZQf7YDRLfT42fPMmGuOCsKOPEk',
    appId: '1:926759717295:android:b0f43439722a7a07ce875a',
    messagingSenderId: '926759717295',
    projectId: 'flutterauth-c90c6',
    storageBucket: 'flutterauth-c90c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVBEYWPvmPSbTQDdh1zxbGI0WI7zTMV0A',
    appId: '1:926759717295:ios:aaeabfd7b7d3b00ace875a',
    messagingSenderId: '926759717295',
    projectId: 'flutterauth-c90c6',
    storageBucket: 'flutterauth-c90c6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVBEYWPvmPSbTQDdh1zxbGI0WI7zTMV0A',
    appId: '1:926759717295:ios:aaeabfd7b7d3b00ace875a',
    messagingSenderId: '926759717295',
    projectId: 'flutterauth-c90c6',
    storageBucket: 'flutterauth-c90c6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrUww1xSkkb_Bdar0rJ-iXUccxSxpT79E',
    appId: '1:926759717295:web:976c6051372f963ece875a',
    messagingSenderId: '926759717295',
    projectId: 'flutterauth-c90c6',
    authDomain: 'flutterauth-c90c6.firebaseapp.com',
    storageBucket: 'flutterauth-c90c6.firebasestorage.app',
    measurementId: 'G-Q0BY18XYFK',
  );
}
